### ISSUE TITLE
On Error, successfull reports are not stored

### ISSUE THREAD

**Issue by basti1508** [antedebaas/DMARC-Reports#40]
If you run app::checkmailbox and within the unread mails is one report, that does cause an error, all other reports from that unread mails are getting tagged read, but not processed to the DB.
The process should handle those errors better.

Here's a trace from when it fails:

```
$ php bin/console app:checkmailbox -vv
[critical] Error thrown while running command "app:checkmailbox -vv". Message: "Call to a member function __toString() on null"
[critical] Uncaught Error: Call to a member function __toString() on null

In CheckmailboxCommand.php line 117:
                                                  
  [Error]                                         
  Call to a member function __toString() on null  
                                                  

Exception trace:
  at /var/www/dmarc-smtptls-reports/src/Command/CheckmailboxCommand.php:117
 App\Command\CheckmailboxCommand->execute() at /var/www/dmarc-smtptls-reports/vendor/symfony/console/Command/Command.php:279
 Symfony\Component\Console\Command\Command->run() at /var/www/dmarc-smtptls-reports/vendor/symfony/console/Application.php:1049
 Symfony\Component\Console\Application->doRunCommand() at /var/www/dmarc-smtptls-reports/vendor/symfony/framework-bundle/Console/Application.php:125
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /var/www/dmarc-smtptls-reports/vendor/symfony/console/Application.php:318
 Symfony\Component\Console\Application->doRun() at /var/www/dmarc-smtptls-reports/vendor/symfony/framework-bundle/Console/Application.php:79
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/dmarc-smtptls-reports/vendor/symfony/console/Application.php:169
 Symfony\Component\Console\Application->run() at /var/www/dmarc-smtptls-reports/vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php:49
 Symfony\Component\Runtime\Runner\Symfony\ConsoleApplicationRunner->run() at /var/www/dmarc-smtptls-reports/vendor/autoload_runtime.php:29
 require_once() at /var/www/dmarc-smtptls-reports/bin/console:11

app:checkmailbox [--option1] [--] [<arg1>]
```

**Comment by antedebaas** [comment]
Yes it should. And it’s on my list :)
I’ll move up the priority

**Comment by antedebaas** [comment]
@basti1508 could you provide an (anonymized) example of the report causing the issue so i can have a detailed look?

**Comment by antedebaas** [comment]
fixed in 1.8.0
see releasenotes https://github.com/antedebaas/DMARC-SMTPTLS-Reports/releases/tag/v1.8.0

**Comment by basti1508** [comment]
sadly. This issue is still there.

I'm not sure, why the try block does not catch the error...

```
In GetReportsFromMailboxCommand.php line 293:
                                                  
  [Error]                                         
  Call to a member function __toString() on null  
                                                  

Exception trace:
  at /var/www/dmarc-smtptls-reports/src/Command/GetReportsFromMailboxCommand.php:293
 App\Command\GetReportsFromMailboxCommand->process_dmarc_report() at /var/www/dmarc-smtptls-reports/src/Command/GetReportsFromMailboxCommand.php:161
 App\Command\GetReportsFromMailboxCommand->process_email() at /var/www/dmarc-smtptls-reports/src/Command/GetReportsFromMailboxCommand.php:99
 App\Command\GetReportsFromMailboxCommand->open_mailbox() at /var/www/dmarc-smtptls-reports/src/Command/GetReportsFromMailboxCommand.php:60
 App\Command\GetReportsFromMailboxCommand->execute() at /var/www/dmarc-smtptls-reports/vendor/symfony/console/Command/Command.php:279
 Symfony\Component\Console\Command\Command->run() at /var/www/dmarc-smtptls-reports/vendor/symfony/console/Application.php:1049
 Symfony\Component\Console\Application->doRunCommand() at /var/www/dmarc-smtptls-reports/vendor/symfony/framework-bundle/Console/Application.php:125
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /var/www/dmarc-smtptls-reports/vendor/symfony/console/Application.php:318
 Symfony\Component\Console\Application->doRun() at /var/www/dmarc-smtptls-reports/vendor/symfony/framework-bundle/Console/Application.php:79
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/dmarc-smtptls-reports/vendor/symfony/console/Application.php:169
 Symfony\Component\Console\Application->run() at /var/www/dmarc-smtptls-reports/vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php:49
 Symfony\Component\Runtime\Runner\Symfony\ConsoleApplicationRunner->run() at /var/www/dmarc-smtptls-reports/vendor/autoload_runtime.php:29
 require_once() at /var/www/dmarc-smtptls-reports/bin/console:11

app:getreportsfrommailbox
```

**Comment by antedebaas** [comment]
Actually the mail causing the problem should now be flagged in your inbox.
Processing would still continue now
Could you find the mail causing the error and post the (anonymized) report here?

**Comment by basti1508** [comment]
But the processing does not Continue. I've tested with 1.8.1 today and the issue persists. I can see the try catch Block in the Code, but the Exception is thrown nevertheless.

**Comment by basti1508** [comment]
here is the file!
[dsea.unipi.it!domain.com!1708543501!1708543501.zip](https://github.com/antedebaas/DMARC-SMTPTLS-Reports/files/14524511/dsea.unipi.it.domain.com.1708543501.1708543501.zip)

**Comment by antedebaas** [comment]
Thanks I’ll look into it

**Comment by antedebaas** [comment]
> here is the file! [dsea.unipi.it!domain.com!1708543501!1708543501.zip](https://github.com/antedebaas/DMARC-SMTPTLS-Reports/files/14524511/dsea.unipi.it.domain.com.1708543501.1708543501.zip)

could you re-upload it? the link seems to be dead

nvm. now the link works again

**Comment by antedebaas** [comment]
fixed in 1.9.0
